import { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import type { NativeStackScreenProps } from '@react-navigation/native-stack';
import type { PlanStackParamList } from '@/navigation/types';
import type { PlanGoalDraft } from '@/types/budget';
import { confirmDraftGoals, getDraftGoals } from '@/services/budget';
import { COLORS, FONTS } from '@/theme';
import { formatCompactVnd, formatMonthYear } from '@/utils/finance';
import { dismissDraftPromptForSession } from './draftPromptSession';

type Props = NativeStackScreenProps<PlanStackParamList, 'DraftPlan'>;
export default function DraftPlanScreen({ navigation }: Props) {
  const [goals, setGoals] = useState<PlanGoalDraft[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [editing, setEditing] = useState<number | 'new' | null>(null); const [name, setName] = useState(''); const [target, setTarget] = useState(''); const [deadline, setDeadline] = useState('');
  useEffect(() => { void getDraftGoals().then((state) => { if (state.confirmed) navigation.goBack(); else setGoals(state.goals); }).catch(() => setError('Không thể tải mục tiêu nháp.')).finally(() => setLoading(false)); }, [navigation]);
  const close = () => { dismissDraftPromptForSession(); navigation.goBack(); };
  const openEditor = (index: number | 'new') => { const goal = index === 'new' ? null : goals[index]; setEditing(index); setName(goal?.name ?? ''); setTarget(goal ? String(Math.round(goal.target_amount)) : ''); setDeadline(goal?.target_date?.slice(0,10) ?? ''); };
  const saveEditor = () => { const amount=Number(target.replace(/[^0-9]/g,'')); if(!name.trim()||!amount){setError('Nhập tên và số tiền mục tiêu.');return;} const goal:PlanGoalDraft={key:editing==='new'?`goal-${Date.now()}`:goals[editing as number].key,name:name.trim(),target_amount:amount,current_amount:editing==='new'?0:goals[editing as number].current_amount,target_date:deadline.trim()||null,goal_type:editing==='new'?'other':goals[editing as number].goal_type,is_primary:editing==='new'?!goals.length:goals[editing as number].is_primary}; setGoals(rows=>editing==='new'?[...rows,goal]:rows.map((row,index)=>index===editing?goal:row)); setEditing(null); setError(''); };
  const confirm = async () => { setSaving(true); setError(''); try { await confirmDraftGoals(goals); dismissDraftPromptForSession(); navigation.goBack(); } catch { setError('Chưa thể xác nhận mục tiêu. Hãy thử lại.'); } finally { setSaving(false); } };
  return <SafeAreaView style={styles.backdrop}><Pressable style={StyleSheet.absoluteFill} onPress={close} accessibilityLabel="Đóng bản mục tiêu nháp" /><View style={styles.card}>
    <View style={styles.head}><View><Text style={styles.title}>Draft Goals</Text><Text style={styles.subtitle}>Kế hoạch mục tiêu nháp</Text></View><Pressable onPress={close}><Ionicons name="close" size={24} color={COLORS.inkSoft} /></Pressable></View>
    <Text style={styles.body}>PocketPilot đã phác thảo các mục tiêu này từ câu trả lời thiết lập của bạn. Hãy xem lại và xác nhận để hoàn tất kế hoạch.</Text>
    {loading ? <ActivityIndicator color={COLORS.greenDeep} /> : <ScrollView>{goals.map((goal, index) => <View key={goal.key} style={styles.goalRow}><View style={styles.icon}><Ionicons name="flag-outline" size={21} color={COLORS.greenDeep} /></View><View style={styles.copy}><Text style={styles.goalName}>{goal.name}</Text><Text style={styles.deadline}>{goal.target_date ? `Deadline: ${formatMonthYear(goal.target_date) ?? goal.target_date}` : 'No deadline'}</Text></View><Text style={styles.amount}>{formatCompactVnd(goal.target_amount)}</Text><Pressable onPress={()=>openEditor(index)} accessibilityLabel={`Chỉnh sửa ${goal.name}`}><Ionicons name="create-outline" size={18} color={COLORS.inkSoft}/></Pressable><Pressable onPress={()=>setGoals(rows=>rows.filter((_,position)=>position!==index))} accessibilityLabel={`Xóa ${goal.name}`}><Ionicons name="trash-outline" size={18} color={COLORS.oxblood}/></Pressable></View>)}{!goals.length?<View style={styles.empty}><Ionicons name="flag-outline" size={30} color={COLORS.textMuted}/><Text style={styles.goalName}>No goals yet</Text><Text style={styles.deadline}>Add a goal, or continue without goals.</Text></View>:null}<Pressable style={styles.addButton} onPress={()=>openEditor('new')}><Ionicons name="add" size={17} color={COLORS.ink}/><Text style={styles.addText}>Add Goal</Text></Pressable></ScrollView>}
    {error ? <Text style={styles.error}>{error}</Text> : null}<Pressable style={styles.button} onPress={() => void confirm()} disabled={saving || loading}>{saving ? <ActivityIndicator color={COLORS.parchment} /> : <Text style={styles.buttonText}>{goals.length?'Confirm Goals':'Continue Without Goals'}</Text>}</Pressable>
    <Modal visible={editing!==null} transparent animationType="fade"><View style={styles.editorBackdrop}><View style={styles.editor}><View style={styles.head}><Text style={styles.title}>{editing==='new'?'Add Goal':'Edit Goal'}</Text><Pressable onPress={()=>setEditing(null)}><Ionicons name="close" size={22} color={COLORS.inkSoft}/></Pressable></View><Text style={styles.fieldLabel}>GOAL NAME</Text><TextInput value={name} onChangeText={setName} style={styles.input}/><Text style={styles.fieldLabel}>TARGET AMOUNT</Text><TextInput value={target} onChangeText={v=>setTarget(v.replace(/[^0-9]/g,''))} keyboardType="number-pad" style={styles.input}/><Text style={styles.fieldLabel}>TARGET DATE (YYYY-MM-DD, OPTIONAL)</Text><TextInput value={deadline} onChangeText={setDeadline} style={styles.input}/><Pressable style={styles.button} onPress={saveEditor}><Text style={styles.buttonText}>Save Goal</Text></Pressable></View></View></Modal>
  </View></SafeAreaView>;
}
const styles=StyleSheet.create({backdrop:{flex:1,justifyContent:'center',padding:24,backgroundColor:'rgba(30,42,50,.55)'},card:{maxHeight:'85%',backgroundColor:COLORS.parchment,borderWidth:2,borderColor:COLORS.ink,padding:24},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},title:{fontFamily:FONTS.display,fontSize:28,color:COLORS.ink},subtitle:{fontFamily:FONTS.mono,fontSize:9,color:COLORS.oxblood,letterSpacing:1},body:{fontSize:14,lineHeight:21,color:COLORS.inkSoft,marginVertical:18},goalRow:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:16,borderBottomWidth:1,borderStyle:'dashed',borderColor:COLORS.border},icon:{width:40,height:40,borderWidth:1,borderColor:COLORS.greenDeep,alignItems:'center',justifyContent:'center'},copy:{flex:1,marginLeft:3},goalName:{fontSize:13,fontWeight:'800',color:COLORS.ink},deadline:{fontSize:10,color:COLORS.textMuted,marginTop:4},amount:{fontFamily:FONTS.mono,fontSize:11,fontWeight:'800',color:COLORS.greenDeep},button:{height:48,alignItems:'center',justifyContent:'center',backgroundColor:COLORS.ink,marginTop:22},buttonText:{fontFamily:FONTS.mono,fontSize:11,fontWeight:'800',textTransform:'uppercase',letterSpacing:1,color:COLORS.parchment},error:{color:COLORS.error,fontSize:11,marginTop:10},empty:{alignItems:'center',padding:20,borderWidth:1,borderStyle:'dashed',borderColor:COLORS.border},addButton:{height:42,flexDirection:'row',alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:COLORS.ink,marginTop:14},addText:{fontFamily:FONTS.mono,fontSize:10,fontWeight:'800',color:COLORS.ink},editorBackdrop:{flex:1,justifyContent:'center',padding:24,backgroundColor:'rgba(30,42,50,.55)'},editor:{backgroundColor:COLORS.parchment,borderWidth:2,borderColor:COLORS.ink,padding:22},fieldLabel:{fontFamily:FONTS.mono,fontSize:9,color:COLORS.oxblood,marginTop:16},input:{borderBottomWidth:1,borderColor:COLORS.ink,paddingVertical:9,color:COLORS.ink}});
